# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1deead7d269f7e29de9c97d8bff3e6c4644c027c68423499fa9ec6489fd5c5dfb4945ffc2145a3dbcf6e4102e4c00be0c97caf077c1ee6dc70e1eeba39d2dc35

test:
  secret_key_base: ffb6a659d42befde391229433349f5381a3d8ebbf53c03c0768869fdfe7c77ce3347e202e0c078b373c60c1a4e4946e8d55590e2500c89d07902e777488facfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
